diffpir:
  task: deblur
  seed: 42

  noise_level_img: 0.05
  noise_level_model: noise_level_img
  model_name: diffusion_ffhq_10m
  testset_name: demo_test
  num_train_timesteps: 1000
  iter_num: 100
  iter_num_U: 1
  batch_size: 16

  save_L: true
  save_E: true

  lambda_: 2
  zeta: 0.25
  sub_1_analytic: true
  log_process: false
  ddim_sample: false
  model_output_type: pred_xstart
  generate_mode: DiffPIR
  skip_type: quad
  eta: 0
  guidance_scale: 1.0 # effective guidance scale
  n_channels: 3
  cwd: ""

  calc_LPIPS: true
  beta_start: 0.0001
  beta_end: 0.02

  noise_init_img: max
  skip_noise_model_t: false

  # deblur
  sf: 1
  use_DIY_kernel: true
  blur_mode: "Gaussian" # Gaussian; motion
  kernel_size: 61

dps_y0:
  task: deblur
  name: dps_y0
  seed: 42

  noise_level_img: 0.05
  noise_level_model: noise_level_img
  model_name: diffusion_ffhq_10m
  testset_name: demo_test
  num_train_timesteps: 1000
  batch_size: 16

  save_L: true
  save_E: true
  output_root: "outputs"

  generate_mode: DPS_y0
  lambda_: 0.1
  zeta: 0.0
  n_channels: 3
  cwd: ""

  calc_LPIPS: true
  sf: 1
  use_DIY_kernel: true
  blur_mode: "Gaussian"
  kernel_size: 61
  kernel_std: 3.0

dps_yt:
  task: deblur
  name: dps_yt
  seed: 42

  noise_level_img: 0.05
  noise_level_model: noise_level_img
  model_name: diffusion_ffhq_10m
  testset_name: demo_test
  num_train_timesteps: 1000
  batch_size: 16

  save_L: true
  save_E: true
  output_root: "outputs"

  generate_mode: DPS_yt
  lambda_: 0.1
  zeta: 0.0
  n_channels: 3
  cwd: ""

  calc_LPIPS: true
  sf: 1
  use_DIY_kernel: true
  blur_mode: "Gaussian"
  kernel_size: 61
  kernel_std: 3.0

pnp_drunet:
  task: deblur

  name: pnp_drunet

  generate_mode: pnp_drunet

  lambda_: 1.0
  zeta: 0.0

  sf: 1

  noise_level_img: 0.05
  noise_level_model: noise_level_img
  blur_mode: "Gaussian" # "Gaussian" or "motion"
  kernel_size: 61
  kernel_std: 3.0

  denoiser: drunet
  num_iters: 200
  step_size: 1.0
  data_weight: 1.0

  denoiser_sigma: 0.008

  gaussian_kernel_size: 5
  gaussian_sigma: 1.0

  calc_LPIPS: true
  save_L: true
  save_E: true
  clamp: true
  output_root: "outputs"

pnp_diffbir:
  task: deblur
  name: pnp_diffbir
  generate_mode: pnp_diffbir

  lambda_: 1.0
  zeta: 0.0
  sf: 1

  denoiser: diffbir
  num_iters: 20
  denoiser_sigma: 0.05
  diffbir_weights_path: ""

  calc_LPIPS: true
  save_L: true
  save_E: true
  clamp: true
  output_root: "outputs"

pnp_gaussian:
  task: deblur
  name: pnp_gaussian
  generate_mode: pnp_gaussian
  lambda_: 1.0
  zeta: 0.0
  sf: 1
  noise_level_img: 0.05
  noise_level_model: noise_level_img
  blur_mode: "Gaussian"
  kernel_size: 61
  kernel_std: 3.0

  denoiser: gaussian
  num_iters: 100
  step_size: 1.0
  data_weight: 1.0
  denoiser_sigma: 0.05
  gaussian_kernel_size: 5
  gaussian_sigma: 0.5
  calc_LPIPS: true
  save_L: true
  save_E: true
  clamp: true
  output_root: "outputs"
