diffpir:
  task: sr
  seed: 42

  noise_level_img: 0.05       # 12.75 / 255
  noise_level_model: 0.05
  model_name: diffusion_ffhq_10m
  testset_name: demo_test
  num_train_timesteps: 1000
  iter_num: 100
  iter_num_U: 1
  batch_size: 16

  save_L: true
  save_E: true

  lambda_: 1.0
  zeta: 0.1
  sub_1_analytic: true
  log_process: false
  ddim_sample: false
  model_output_type: pred_xstart
  generate_mode: DiffPIR
  skip_type: quad
  eta: 0.0
  guidance_scale: 1.0
  n_channels: 3
  cwd: ''

  calc_LPIPS: true
  beta_start: 0.0001
  beta_end: 0.02

  # sr
  sf: 4
  sr_mode: blur             # blur | cubic
  classical_degradation: false
  inIter: 1                 # IBP inner iterations (cubic mode only)
  gamma: 0.01               # IBP step size (cubic mode only)
